cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

citygreens/urls.py
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static 
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^account/', include('account.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^favorites/', include('favorites.urls', namespace='favorites'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),	
]

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'home/home.html', {'section': 'home'})

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href=" ">
<title>CityGreens Home</title>

<!-- Bootstrap core CSS -->
<link href="static/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="static/css/custom.css" rel="stylesheet">
<link href="{% static "css/base.css" %}" rel="stylesheet">

<!-- Helper Styles -->
<link href="static/css/loaders.css" rel="stylesheet">
<link href="static/css/swiper.min.css" rel="stylesheet">
<link rel="stylesheet" href="static/css/animate.min.css">
<link rel="stylesheet" href="static/css/nivo-lightbox.css">
<link rel="stylesheet" href="static/css/nivo_themes/default/default.css">
<!-- Font Awesome Style -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<div id="header">
    <a href="/" class="logo"><img src="{% static "img/logo.png" %}"> </a>
</div>
<div id="subheader">
    <ul class="menu">
        <li {% if section == "home" %}class="selected"{% endif %}><a href="{% url "home" %}">Home</a></li>  
         <li {% if section == "shop" %}class="selected"{% endif %}><a href="{% url "shop:product_list" %}">Shop</a></li>     
        {% if request.user.is_authenticated %}
        <li {% if section == "dashboard" %}class="selected"{% endif %}><a href="{% url "dashboard" %}">My profile</a></li>
        {% endif %}
    </ul>

    <span class="user">
    {% if request.user.is_authenticated %}
        Hi! {{ request.user }}, <a href="{% url "logout" %}">Logout</a>
    {% else %}
        <a href="{% url "login" %}">Log-in</a>
    {% endif %}
    </span>
    
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart: 
                <a href="{% url "cart:cart_detail" %}">
                    {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.
            {% endif %}
        {% endwith %}
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>

<div class="loader loader-bg">
  <div class="loader-inner ball-clip-rotate-pulse">
    <div></div>
    <div></div>
  </div>
</div>

<!-- Swiper Silder
    ================================================== --> 
<!-- Slider main container -->
<div class="swiper-container main-slider" id="myCarousel">
  <div class="swiper-wrapper">
    <div class="swiper-slide slider-bg-position" style="background:url('static/img/1.jpg')" data-hash="slide1">
      <h2>An easy way to consume fresh products </h2>
    </div>
    <div class="swiper-slide slider-bg-position" style="background:url('static/img/3.jpg')" data-hash="slide2">
      <h2>Get fruit and vegetables of the season!</h2>
    </div>
  </div>
  <!-- Add Pagination -->
  <div class="swiper-pagination"></div>
  <!-- Add Navigation -->
  <div class="swiper-button-prev"><i class="fa fa-chevron-left"></i></div>
  <div class="swiper-button-next"><i class="fa fa-chevron-right"></i></div>
</div>

<!-- Benefits
    ================================================== -->
<section class="service-sec" id="benefits">
  <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="heading text-md-center text-xs-center">
      <h2><small>Advantages of buying on CityGreens</small>Place your order, we deal with the rest</h2>
    </div>
        </div>
      <div class="col-md-12">
        <div class="row">
            <div class="col-md-6 text-sm-center service-block"> <img style = "padding-bottom: 20px;"src="static/img/advquality.jpg" class="img-fluid col-md-6" />
          <h3>Quality assurance</h3>
          <p>At citygreens we ensure the best suppliers of fruit and vegetables so you can enjoy fresh and organic products of higher quality.</p>
        </div>
        <div class="col-md-6 text-sm-center service-block"> <img style = "padding-bottom: 20px;"src="static/img/advseason.jpg" class="img-fluid col-md-6" />
          <h3>Seasonal products</h3>
          <p>We carefully select the best fruits of the season for you. Try our baskets ready to be delivered to your home.</p>
        </div>
        <div class="col-md-6 text-sm-center service-block"> <img style = "padding-bottom: 20px;"src="static/img/side-01.jpg" class="img-fluid col-md-6" />
          <h3>Fast delevery</h3>
          <p>Fast and convenient delivery to the best products arrive your home as they left the greenhouse</p>
        </div>
        <div class="col-md-6 text-sm-center service-block"> <img style = "padding-bottom: 20px;"src="static/img/advmulti.png" class="img-fluid col-md-6" />
          <h3>We are multi-plataform</h3>
          <p>Our simple and intuitive platform can be accessed anywhere, whether on your PC in the comfort of your home or in the garden park through your personal smartphone!</p>
        </div>
        </div>
      </div>
    </div>
    <!-- /.row --> 
  </div>
</section>

<!-- About 
    ================================================== -->
<section class="about-sec parallax-section" id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2><small>Who We Are</small>About<br>
          CityGreens</h2>
      </div>
      <div class="col-md-4">
        <p>We are a company based in Portugal that together with our affiliate ActiveVeg we deal in the trade of food products produced in our greenhouses scattered throughout the country.</p>
      </div>
      <div class="col-md-4">
        <p> Through our online platform we aim to create an easy and versatile experience so that everyone can get fresh fruits and vegetables quickly without leaving the comfort of their home's.</p>
        <p><a href="{% url "shop:product_list" %}" class="btn btn-transparent-white btn-capsul">Explore our store</a></p>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row copy-footer">
      <div class="col-md-6 col-xs-12"> &copy;<script type="text/javascript">document.write(new Date().getFullYear());</script> CityGreens - All rights reserved </div>
      <div class="col-md-6 col-xs-12 text-xs-right">Created with <i class="fa fa-heart"></i></div>
    </div>
  </div>
</footer>

<!-- Bootstrap core JavaScript
    ================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="static/js/jquery.min.js" ></script> 
<script src="static/js/bootstrap.min.js"></script> 
<script src="static/js/scrollPosStyler.js"></script> 
<script src="static/js/swiper.min.js"></script> 
<script src="static/js/isotope.min.js"></script> 
<script src="static/js/nivo-lightbox.min.js"></script> 
<script src="static/js/wow.min.js"></script> 
<script src="static/js/core.js"></script> 

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug --> 
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>